export enum PIECE {
  BlackAdvisor = 'A',
  BlackBishop = 'B',
  BlackCannon = 'C',
  BlackGeneral = 'K',
  BlackHorse = 'H',
  BlackPawn = 'P',
  BlackChariot = 'R',
  RedAdvisor = 'a',
  RedBishop = 'b',
  RedCannon = 'c',
  RedGeneral = 'k',
  RedHorse = 'h',
  RedPawn = 'p',
  redChariot = 'r',
}
